### ISSUE TITLE
一些bug反馈

### ISSUE THREAD

**Issue by Zisbusy** [shiqizhenyes/ShadowsocksX-NG-R8#1]
Mac OS Big Sur 11.2.1
不能正常使用，节点正常。
帮助-问题反馈处url 不是本项目issues
帮助-检查更新 失败

**Comment by shiqizhenyes** [comment]
升级至mac 最新系统吧，我自己的电脑是跟着升级的，也没法降级

**Comment by shiqizhenyes** [comment]
> Mac OS Big Sur 11.2.1 不能正常使用，节点正常。 帮助-问题反馈处url 不是本项目issues 帮助-检查更新 失败

升级至mac 最新系统吧，我自己的电脑是跟着升级的，也没法降级

**Comment by shiqizhenyes** [comment]
> Mac OS Big Sur 11.2.1 不能正常使用，节点正常。 帮助-问题反馈处url 不是本项目issues 帮助-检查更新 失败

后面两个问题，在下个版本修复

**Comment by shiqizhenyes** [comment]
> Mac OS Big Sur 11.2.1 不能正常使用，节点正常。 帮助-问题反馈处url 不是本项目issues 帮助-检查更新 失败

可以先到软件设置里点击系统看一下Wi-Fi 有没有勾上，没有的勾上保存，关闭重新开启一次代理应该就好了

**Comment by gongchao8888** [comment]
12.1版本系统可以用吗

**Comment by shiqizhenyes** [comment]
> 12.1版本系统可以用吗

经验证 无论是英特尔还是m1 的mac 在 12.1 上都是可用的

**Comment by shiqizhenyes** [comment]
> 12.1版本系统可以用吗

我建议你先按我上面说的检查一下，再考虑系统升级

**Comment by gongchao8888** [comment]
可以使用，M1pro 12.11 系统，但是为什么打开 ShadowsocksX 后 后台会出现两个进程  privoxy 和 ss-local

**Comment by gongchao8888** [comment]
> 

可以使用，M1pro 12.11 系统，但是为什么打开 ShadowsocksX 后 后台会出现两个进程 privoxy 和 ss-local



> > 12.1版本系统可以用吗
> 
> 我建议你先按我上面说的检查一下，再考虑系统升级

可以使用，M1pro 12.11 系统，但是为什么打开 ShadowsocksX 后 后台会出现两个进程 privoxy （Intel）和 ss-local （intel）

**Comment by gongchao8888** [comment]
> 



> > 12.1版本系统可以用吗
> 
> 我建议你先按我上面说的检查一下，再考虑系统升级

可以使用，M1pro 12.11 系统，但是为什么打开 ShadowsocksX-NG-R8后 后台会出现两个进程 privoxy （Intel）和 ss-local （intel）

**Comment by shiqizhenyes** [comment]
> > 
> 
> > > 12.1版本系统可以用吗
> > 
> > 
> > 我建议你先按我上面说的检查一下，再考虑系统升级
> 
> 可以使用，M1pro 12.11 系统，但是为什么打开 ShadowsocksX-NG-R8后 后台会出现两个进程 privoxy （Intel）和 ss-local （intel）

不影响用，下次编译我留意下，我没有m1 的电脑测试，暂时不是很清楚
